#!/usr/bin/env bash
# Puts `pf` on the PATH, pointing at a build in this tree.
#
# Usage: scripts/install-cli.sh [preset] [destination]
#   preset       release (default) or dev
#   destination  ~/.local/bin by default
set -euo pipefail

preset=${1:-release}
destination=${2:-$HOME/.local/bin}
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
target=$destination/pf

if [[ $OSTYPE == darwin* ]]; then
    binary=$root/build/$preset/bin/Panefile.app/Contents/MacOS/Panefile
else
    binary=$root/build/$preset/bin/pf
fi

if [[ ! -x $binary ]]; then
    echo "no binary at $binary — build the $preset preset first" >&2
    exit 1
fi

mkdir -p "$destination"

# Remove first, rather than letting the redirection below overwrite in place.
# If $target is an existing symlink — which is exactly what this script is here
# to replace — `cat >` follows it and writes to whatever it points at. Pointed
# into the bundle, as the old one was, that means overwriting the application's
# own executable with this wrapper.
rm -f "$target"

# A wrapper that execs, not a symlink.
#
# On macOS a symlink breaks the application's identity: CFBundleGetMainBundle
# works out what is running from the executable's path, and the kernel reports
# the path the process was launched by rather than the one the symlink resolves
# to. The bundle is never found, so there is no Info.plist — the app shows the
# grey placeholder icon in the Dock and calls itself "pf" instead of "Panefile".
#
# exec replaces this shell with the real executable at its real path, which is
# all it takes for macOS to recognise the bundle. On Linux it costs nothing and
# keeps one code path.
cat > "$target" <<WRAPPER
#!/bin/sh
# Generated by scripts/install-cli.sh — points at the $preset build.
exec "$binary" "\$@"
WRAPPER
chmod +x "$target"

echo "installed $target -> $binary"
